function [mapobj , revmapobj] = MapSets()
    key = {'0','1','2','3','4','5','6','7',...
        'lplet','rplet',...
        'dot','accent','sharp','flat','nature',...
        'graceOne','breathe','barline','frontRepeat',...
        'backRepeat','lt','rt','lessThan',...
        's','turtle'};
    value = 1:size(key,2);
    %%
    mapobj = containers.Map(key,value);
    revmapobj = containers.Map(value,key);
end
